import { FormEvent, useEffect, useState, type ReactNode } from "react";
import { ArrowUpLeft, ArrowUpRight, Check, ChevronDown, Code2, Layers3, Menu, MessageCircle, Palette, Send, Sparkles, Star, X } from "lucide-react";

const whatsappNumber = "201050094382";
const nav = [["الخدمات", "#services"], ["أعمالنا", "#work"], ["الفريق", "#team"], ["التقييمات", "#testimonials"], ["الأسئلة", "#faq"]] as const;
const services = [
  { icon: Code2, number: "01", label: "PRODUCT ENGINEERING", title: "تطوير منتجات رقمية", copy: "نحوّل الفكرة إلى منتج سريع، مرتب، وقابل للتوسع — من أول شاشة إلى أول عميل.", tags: ["Web Apps", "Dashboards", "MVP"] },
  { icon: Layers3, number: "02", label: "UX / UI DESIGN", title: "تجربة وواجهات", copy: "نصمم تجربة يفهمها المستخدم من أول لحظة، وتحافظ على شخصية البراند في كل تفصيلة.", tags: ["UX Strategy", "UI Systems", "Prototype"] },
  { icon: Palette, number: "03", label: "BRAND SYSTEMS", title: "هوية بصرية كاملة", copy: "نصنع نظامًا بصريًا واضحًا يخلّي العلامة ثابتة، مميزة، وقابلة للاستخدام يوميًا.", tags: ["Branding", "Social", "Art Direction"] },
];
const team = [
  { initials: "SC", name: "Hazem Mohammed Kamel", role: "Founder · Full-Stack Developer", copy: "يقود الرؤية ويجمع بين المنتج، الكود، والتصميم في حل واحد." },
  { initials: "A", name: "Abdulrahman", role: "Senior Software Engineer", copy: "مبرمج محترف بخبرة 5 سنين في بناء حلول مستقرة وسريعة." },
  { initials: "M", name: "Moaz", role: "Graphic Designer", copy: "مصمم جرافيكس بخبرة 6 سنين في بناء هويات لها حضور." },
  { initials: "MT", name: "Maryam Tarek", role: "Websites Developer", copy: "مبرمجة مواقع تهتم بالتفاصيل، سهولة الاستخدام، وبناء تجارب ويب واضحة وسريعة." },
];
const faqs = [
  ["هل SCORPIUS فريق أم شخص واحد؟", "SCORPIUS استوديو وفريق متكامل في البرمجة والتصميم والهوية البصرية. تشكيل الفريق يختلف حسب احتياج المشروع."],
  ["ما الذي أستلمه بعد المشروع؟", "تستلم المنتج أو الموقع، الملفات المتفق عليها، وملخصًا واضحًا لما تم تنفيذه وطريقة تشغيله."],
  ["كيف نبدأ؟", "أرسل لنا فكرتك على واتساب. نرد عليك بنطاق مبدئي وخطوة تالية واضحة قبل بدء التنفيذ."],
  ["هل يوجد دعم بعد الإطلاق؟", "نعم. يوجد دعم لأخطاء التسليم، ويمكن الاتفاق على تطوير وصيانة مستمرة حسب احتياجك."],
];
const steps = ["نسمع ونحدد", "نرسم المسار", "نبني ونراجع", "نطلق ونسلّم"];
const testimonials = [
  { quote: "فريق SCORPIUS من أفضل الفرق التي تعاملنا معها. جمعوا بين التفكير الذكي والتنفيذ المنظم وقدموا لنا نتيجة نفتخر بها.", name: "عميل موثّق", role: "شهادة عن جودة الفريق", mark: "01" },
  { quote: "التصميمات عصرية وجديدة ومبتكرة، وفي نفس الوقت واضحة وسهلة الاستخدام. التجربة النهائية كانت أفضل مما توقعنا.", name: "عميل موثّق", role: "شهادة عن التصميم وتجربة الاستخدام", mark: "02" },
  { quote: "المواقع التي نفذها الفريق سهلة التعامل وغير معقدة. اهتموا بتفاصيل رحلة المستخدم، وده ظهر في النتيجة بشكل واضح.", name: "عميل موثّق", role: "شهادة عن سهولة الاستخدام", mark: "03" },
  { quote: "أكثر شيء ميّز التعاون هو الالتزام بالمواعيد ووضوح التواصل. كل مرحلة كانت منظمة والتسليم تم في الوقت المتفق عليه.", name: "عميل موثّق", role: "شهادة عن الالتزام بالمواعيد", mark: "04" },
];

function Logo() {
  return <a className="logo" href="#top" aria-label="SCORPIUS home"><span className="logo-image"><img src="/scorpius-logo.jpg" alt="SCORPIUS scorpion logo" /></span><span className="logo-name">SCORPIUS</span><span className="logo-dot">/.</span></a>;
}
function Kicker({ children, number }: { children: ReactNode; number: string }) { return <div className="kicker"><span>{number}</span><i />{children}</div>; }
function WhatsApp({ children, secondary = false }: { children: ReactNode; secondary?: boolean }) { return <a className={`button ${secondary ? "button-secondary" : "button-primary"}`} href={`https://wa.me/${whatsappNumber}`} target="_blank" rel="noreferrer">{children}<ArrowUpLeft size={16} /></a>; }

export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [faqOpen, setFaqOpen] = useState(0);
  const [form, setForm] = useState({ name: "", service: "منتج رقمي", message: "" });
  useEffect(() => {
    const observer = new IntersectionObserver((entries) => entries.forEach((entry) => { if (entry.isIntersecting) { entry.target.classList.add("is-visible"); observer.unobserve(entry.target); } }), { threshold: 0.14 });
    document.querySelectorAll(".reveal-on-scroll").forEach((element) => observer.observe(element));
    return () => observer.disconnect();
  }, []);
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const text = `مرحباً SCORPIUS، أنا ${form.name || "عميل جديد"}. مهتم بـ ${form.service}. ${form.message || "أرغب في مناقشة فكرة مشروع."}`; window.open(`https://wa.me/${whatsappNumber}?text=${encodeURIComponent(text)}`, "_blank", "noopener,noreferrer"); };

  return <div className="app" id="top">
    <div className="noise" />
    <header className="header"><div className="wrap header-inner"><Logo /><nav className={menuOpen ? "nav open" : "nav"}>{nav.map(([label, href], index) => <a key={href} href={href} onClick={() => setMenuOpen(false)}><small>0{index + 1}</small>{label}</a>)}<WhatsApp>ابدأ مشروعك</WhatsApp></nav><button className="menu" onClick={() => setMenuOpen(!menuOpen)} aria-label="القائمة">{menuOpen ? <X /> : <Menu />}</button></div></header>
    <main>
      <section className="hero reveal-on-scroll is-visible"><div className="hero-bg"><div className="hero-rings" /><div className="hero-code"><span>SCORPIUS / STUDIO</span><strong>build<br /><em>with intent.</em></strong><small>01 strategy<br />02 design<br />03 engineering</small></div></div><div className="wrap hero-content"><div className="hero-copy"><div className="eyebrow"><span /> DIGITAL PRODUCT STUDIO <b>EST. 2026</b></div><h1>نبني لك<br /><span>حضورًا حقيقيًا.</span></h1><p>استوديو SCORPIUS يجمع البرمجة، التصميم، والهوية البصرية في فريق واحد عشان تطلع بفكرة متماسكة وجاهزة للسوق.</p><div className="hero-actions"><WhatsApp>احكِ لنا عن فكرتك</WhatsApp><a className="link" href="#work">شاهد أعمالنا <ArrowUpLeft size={16} /></a></div><div className="stats"><div><b>01</b><span>فريق واحد<br />من الفكرة للإطلاق</span></div><div><b>100%</b><span>وضوح في النطاق<br />والتسليم</span></div><div><b>360°</b><span>كود، تصميم<br />وهوية</span></div></div></div></div><div className="scroll">SCROLL <ArrowUpRight size={14} /></div></section>
      <div className="ticker"><div>PRODUCT STRATEGY <b>✳</b> DESIGN SYSTEMS <b>✳</b> FULL-STACK BUILD <b>✳</b> BRAND DIRECTION <b>✳</b> PRODUCT STRATEGY <b>✳</b></div></div>
      <section className="section reveal-on-scroll" id="services"><div className="wrap"><div className="heading two"><div><Kicker number="01">WHAT WE DO</Kicker><h2>مش مجرد تنفيذ.<br /><span>بناء له معنى.</span></h2></div><p>كل خدمة عندنا جزء من رحلة أكبر: نفهم المشكلة، نرتب الأولويات، ونبني الحل الذي يستحق أن يعيش في السوق.</p></div><div className="service-grid">{services.map(({ icon: Icon, number, label, title, copy, tags }) => <article className="service" key={number}><div className="service-top"><b>{number}</b><Icon /></div><div><small>{label}</small><h3>{title}</h3><p>{copy}</p><div className="tags">{tags.map(tag => <span key={tag}>{tag}</span>)}</div></div><ArrowUpLeft className="arrow" /></article>)}</div></div></section>
      <section className="section work reveal-on-scroll" id="work"><div className="wrap"><div className="heading"><Kicker number="02">SELECTED WORK</Kicker><h2>أعمال نقدر<br /><span>نتكلم عنها.</span></h2><p>كل مشروع يبدأ بسؤال واضح وينتهي بتجربة لها هدف. دي عينة من طريقة تفكيرنا.</p></div><div className="projects"><a className="project project-main" href="https://qureo-plus.vercel.app" target="_blank" rel="noreferrer"><div className="project-art qureo"><span>QUREO / 01—73</span><strong>QUREO<br /><em>PLUS</em></strong><b>73<small> LEVELS<br />TO MASTER</small></b><code>const <i>learn</i> = build(idea);</code></div><div className="project-info"><div><small>EDUCATIONAL PRODUCT · 2026</small><h3>Qureo Plus</h3><p>منصة تعليمية لمسارات JavaScript وPython بتجربة تعلم منظمة.</p></div><ArrowUpLeft /></div></a><article className="project"><div className="project-art identity"><span>IDENTITY SYSTEM / 02</span><strong>BRAND<br /><em>IN MOTION</em></strong><b>/\</b></div><div className="project-info"><div><small>BRAND IDENTITY · CONCEPT</small><h3>هوية تتحرك معك</h3><p>أنظمة بصرية للعلامات التي تريد أن تظهر بثقة.</p></div><ArrowUpLeft /></div></article></div></div></section>
      <section className="section team reveal-on-scroll" id="team"><div className="wrap"><div className="heading two"><div><Kicker number="03">THE PEOPLE BEHIND IT</Kicker><h2>أفكار مختلفة.<br /><span>فريق واحد.</span></h2></div><p>القوة مش في عدد الأفراد، لكن في إن كل شخص يضيف زاوية مختلفة لنفس الهدف.</p></div><div className="team-grid">{team.map((member, index) => <article className={`member member-${index}`} key={member.name}><div className="avatar"><span>{member.initials}</span><i /><i /></div><small>{member.role}</small><h3>{member.name}</h3><p>{member.copy}</p><div className="member-foot"><Check size={14} /> SCORPIUS CORE TEAM</div></article>)}</div><div className="team-note"><Sparkles size={16} /> فريق صغير بما يكفي للمرونة، وخبير بما يكفي لبناء شيء يعتمد عليه.</div></div></section>
      <section className="section testimonials reveal-on-scroll" id="testimonials"><div className="wrap"><div className="heading two"><div><Kicker number="04">CLIENT VOICE</Kicker><h2>الثقة تبدأ<br /><span>من تجربة حقيقية.</span></h2></div><p>آراء حقيقية من عملاء وافقوا على مشاركة تجربتهم مع SCORPIUS — من جودة الفريق والتصميم إلى سهولة الاستخدام والالتزام بالمواعيد.</p></div><div className="testimonial-grid">{testimonials.map((item) => <article className="testimonial" key={item.mark}><div className="testimonial-top"><span>{item.mark}</span><div className="stars">{Array.from({ length: 5 }).map((_, index) => <Star key={index} size={14} fill="currentColor" />)}</div></div><p>“{item.quote}”</p><div className="testimonial-person"><span className="person-mark">{item.mark}</span><div><strong>{item.name}</strong><small>{item.role}</small></div></div></article>)}</div><div className="review-note"><Star size={15} fill="currentColor" /> كل شهادة هنا مقدمة بموافقة صاحبها، ونحافظ على خصوصية الأسماء عند عدم طلب نشرها.</div></div></section>
      <section className="section process reveal-on-scroll"><div className="wrap process-grid"><div className="heading"><Kicker number="05">HOW WE WORK</Kicker><h2>الطريق<br /><span>واضح.</span></h2><p>لا قفزات مجهولة ولا تسليم مفاجئ. كل مرحلة لها قرار ومخرج مفهوم.</p><WhatsApp secondary>ابدأ محادثة</WhatsApp></div><div className="steps">{steps.map((step, index) => <div className="step" key={step}><b>0{index + 1}</b><div><h3>{step}</h3><p>{["نفهم الهدف والجمهور والقيود قبل أي تصميم أو كود.", "نحوّل الفكرة إلى نطاق واضح وأولويات قابلة للتنفيذ.", "تصميم ثم تطوير ثم مراجعة مستمرة بدون مفاجآت.", "نختبر ونطلق ونسلّمك المنتج والمعرفة اللازمة."][index]}</p></div></div>)}</div></div></section>
      <section className="section faq reveal-on-scroll" id="faq"><div className="wrap faq-grid"><div className="heading"><Kicker number="06">GOOD TO KNOW</Kicker><h2>أسئلة قبل<br /><span>ما نبدأ.</span></h2><p>لو سؤالك مش هنا، ابعته لنا مباشرة وسنرد عليك بتفاصيل تناسب مشروعك.</p></div><div className="faq-list">{faqs.map(([question, answer], index) => <div className={faqOpen === index ? "faq-item active" : "faq-item"} key={question}><button onClick={() => setFaqOpen(faqOpen === index ? -1 : index)}><span>{question}</span><ChevronDown /></button><p>{answer}</p></div>)}</div></div></section>
      <section className="contact reveal-on-scroll" id="contact"><div className="wrap contact-grid"><div className="contact-copy"><Kicker number="07">LET'S MAKE IT REAL</Kicker><h2>جاهز تطلع<br /><span>الفكرة للسوق؟</span></h2><p>اكتب لنا سطرين عن مشروعك، وسنرجع لك بخطوة تالية واضحة.</p><a href={`https://wa.me/${whatsappNumber}`} target="_blank" rel="noreferrer"><MessageCircle size={18} /> تواصل مباشر على واتساب <ArrowUpLeft size={15} /></a></div><form onSubmit={submit}><div className="form-head"><span>START A PROJECT</span><span>01 / 01</span></div><label>الاسم<input value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} placeholder="اسمك أو اسم الشركة" /></label><label>نوع المشروع<select value={form.service} onChange={e => setForm({ ...form, service: e.target.value })}><option>منتج رقمي</option><option>موقع شركة</option><option>هوية بصرية</option><option>متجر إلكتروني</option><option>مشروع مخصص</option></select></label><label>احكِ لنا أكثر<textarea value={form.message} onChange={e => setForm({ ...form, message: e.target.value })} placeholder="الفكرة، الجمهور، والموعد المتوقع…" rows={4} /></label><button className="button button-primary submit" type="submit">أرسل التفاصيل على واتساب <Send size={16} /></button></form></div></section>
    </main>
    <footer><div className="wrap footer-top"><Logo /><p>WE BUILD THE THINGS<br /><span>PEOPLE REMEMBER.</span></p><a href="#top">العودة للأعلى <ArrowUpRight size={15} /></a></div><div className="wrap footer-bottom"><span>© 2026 SCORPIUS STUDIO</span><span>CRAFTED IN-HOUSE · DELIVERED WITH PRECISION</span><span>WHATSAPP · EMAIL</span></div></footer><a className="floating" href={`https://wa.me/${whatsappNumber}`} target="_blank" rel="noreferrer" aria-label="واتساب"><MessageCircle /></a>
  </div>;
}
